Sprint10
desikvasya/imageFeed pull request #3
Opened 2023-02-11 01:56 UTC by desikvasya

Исправления после код ревью

2023-02-11 09:10 UTC, mmbabaev requested changes

2023-02-11 09:10 UTC, mmbabaev commented on Image Feed.xcodeproj/project.pbxproj
> +		928EF96F2995273F00B65FEC /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = "../../Downloads/Sprint_10_-_Lesson_7_-_1_-_SplashViewController/Image Feed/B
вот здесь произошли странные изменения

2023-02-11 09:10 UTC, mmbabaev commented on Image Feed.xcodeproj/project.pbxproj
> +		928EF96F2995273F00B65FEC /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = "../../Downloads/Sprint_10_-_Lesson_7_-_1_-_SplashViewController/Image Feed/B
<img width="842" alt="Screenshot 2023-02-11 at 12 09 55" src="https://user-images.githubusercontent.com/12600807/218250233-0b68e778-ea85-4344-9b39-8ed3cee140d9.png">

2023-02-12 02:12 UTC, desikvasya commented on Image Feed.xcodeproj/project.pbxproj
> +		928EF96F2995273F00B65FEC /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = "../../Downloads/Sprint_10_-_Lesson_7_-_1_-_SplashViewController/Image Feed/B
@mmbabaev сделал новый пуля реквест, потому что после исправлений не все файлы косматились и пушились в эту ветку. Посмотри пожалуйста. Наставник сказал, что все нормально. Подробную обратную связь не дали, посмотри пожалуйста если все ок, я выложу в практикуме
https://github.com/desikvasya/imageFeed/pull/4

2023-02-24 03:28 UTC, merged